### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by BinaryBrain** [BinaryBrain/HEIGre-doux#3]
### SQL

- [ ] SQL script to populate table `Aliments`
- [ ] SQL script to populate table `NutrimentsAliments`, `NutrimentsNames` `NutrimentsValues`
- [ ] Call SQL procedure to increment `Aliments.occurrence`

### Web

- [ ] Admin interface to set Nutriments
- [ ] Votes
- [ ] Refresh button

### Other

- [ ] Do every in-code TODOs
